name: Maven Run Tests when push to Main branch and newly created PRs.

on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                java-version: '11'
            - name: Build with Maven
              run: mvn clean install
              working-directory: back
            - name: Run Jacoco tests
              run: mvn test jacoco:report
              working-directory: back
            - name: Get Jacoco report
              uses: actions/upload-artifact@v2
              with:
                name: jacoco-report
                path: back/target/site/jacoco
