name: CI/CD pipeline

on: [push]

jobs:

    Backend_tests:
        name: Backend tests with coverage
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: back
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Set up JDK 11
              uses: actions/setup-java@v4
              with:
                java-version: '11'
                distribution: 'temurin'
                architecture: x64
                cache: 'maven'
            - name: Build with Maven
              run: mvn clean install
            - name: Run Jacoco tests
              run: mvn test jacoco:report
            - name: Upload Jacoco report
              uses: actions/upload-artifact@v4
              with:
                name: backend-jacoco-report
                path: back/target/site/jacoco

    Frontend_tests:
        name: Frontend tests with coverage
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: front
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '14'
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage
            - name: Upload coverage report
              uses: actions/upload-artifact@v4
              with:
                  name: frontend-coverage-report
                  path: front/coverage/bobapp/

    SonarCloud_quality:
        name: SonarCloud backend & frontend quality
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
              
          - name: Use Node.js
            uses: actions/setup-node@v4
            with:
                node-version: '14'
          - name: Install dependencies
            working-directory: front
            run: npm ci
          - name: Run frontend tests
            run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage
            working-directory: front
            
          - name: Set up JDK 17
            uses: actions/setup-java@v4
            with:
              java-version: '17'
              distribution: 'temurin'
          - name: Cache SonarCloud packages
            uses: actions/cache@v4
            with:
              path: ~/.sonar/cache
              key: ${{ runner.os }}-sonar
              restore-keys: ${{ runner.os }}-sonar
          - name: Cache Maven packages
            uses: actions/cache@v4
            with:
              path: ~/.m2
              key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
              restore-keys: ${{ runner.os }}-m2
          - name: Build with Maven
            working-directory: back
            run: mvn clean package

          - name: SonarCloud Scan
            uses: SonarSource/sonarcloud-github-action@master
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            with:
                projectBaseDir: .
