name: CI/CD pipeline

on: [push]

jobs:

    Backend_tests:
        name: Backend tests with coverage
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: back
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'
                architecture: x64
                cache: 'maven'
            - name: Build with Maven
              run: mvn clean install
            - name: Run Jacoco tests
              run: mvn test jacoco:report
            - name: Upload Jacoco report
              uses: actions/upload-artifact@v3
              with:
                name: jacoco-report
                path: back/target/site/jacoco
            - name: Get coverage info
              run: echo "Total coverage of ${{ steps.jacoco.outputs.coverage-overall }}"

    Frontend_tests:
        name: Frontend tests with coverage
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: front
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '14'
                  cache: 'npm'
            - name: Install dependencies
              run: |
                  npm install
                  npm ci
            - name: Run tests
              run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage
            - name: Upload coverage report
              uses: actions/upload-artifact@v3
              with:
                  name: frontend-coverage-report
                  path: front/coverage/bobapp/
